#!/bin/bash

# starting
echo "[wx] starting compilation..."

# set path
pushd ~/a/waax

# launch compiler
java -jar compiler.jar --language_in ECMASCRIPT5 \
--js=src/core/Monkey.js \
--js=src/core/WAAX.js \
--js=src/core/Utils.js \
--js=src/core/Builtin.js \
--js=src/core/Unit.js \
--js=src/generator/Oscil.js \
--js=src/generator/Fmop.js \
--js=src/generator/Noise.js \
--js=src/generator/ITrain.js \
--js=src/generator/ITrain2.js \
--js=src/generator/Sampler.js \
--js=src/generator/Step.js \
--js=src/processor/Fader.js \
--js=src/processor/ADSR.js \
--js=src/processor/Filter.js \
--js=src/processor/Formant.js \
--js=src/processor/FormantV.js \
--js=src/processor/Chorus.js \
--js=src/processor/Phasor.js \
--js=src/processor/Comp.js \
--js=src/processor/Pingpong.js \
--js=src/processor/Converb.js \
--js=src/core/Boot.js \
--js_output_file=build/waax.min.js

# revert path
popd

# confirm
echo "[wx] completed."