#!/bin/bash
#
pushd ~/a/waax
java -jar compiler.jar \
--js=src/core/WAAX.js \
--js=src/core/Unit.js \
--js=src/core/Helper.js \
--js=src/core/Internal.js \
--js=src/core/Template.js \
--js=src/core/Time.js \
--js=src/units/generators/LFO.js \
--js=src/units/generators/Noise.js \
--js=src/units/generators/Oscil.js \
--js=src/units/generators/ImpTrain.js \
--js=src/units/generators/Sampler.js \
--js=src/units/processors/ADSR.js \
--js=src/units/processors/C2.js \
--js=src/units/processors/Comp.js \
--js=src/units/processors/ConVerb.js \
--js=src/units/processors/Fader.js \
--js=src/units/processors/LPF.js \
--js=src/units/processors/ModLPF.js \
--js=src/units/processors/TwinDelay.js \
--js=src/units/analyzers/Waveform.js \
--js=src/units/analyzers/Spectrum.js \
--js=src/units/analyzers/Visualizer.js \
--js=src/ui/UIManager.js \
--js=src/ui/UISliderH.js \
--js=src/ui/UISliderV.js \
--js=src/ui/UIKnob.js \
--js_output_file=build/WAAX.min.js
popd