#!/bin/bash

# USAGE
# ./update-waax 'commit message'

# rsync core, data, examples 
# from waax to waax-pages
rsync -avz ~/a/waax/core/* ~/a/waax-pages/core
rsync -avz ~/a/waax/data/* ~/a/waax-pages/data
rsync -avz ~/a/waax/examples/* ~/a/waax-pages/examples

# pushd to waax
# add all changes to git
# commit to local repo
# push to origin master
pushd ~/a/waax
git add -A
git commit -m"$1"
git push origin master
popd

# cd to waax-pages
# add all changes to git
# commit to local repo
# push to origin master
pushd ~/a/waax-pages
git add -A
git commit -m"$1"
git push origin gh-pages
popd